add dockerfiles, remove requested

diff --git a/hub.docker.com/bland328/node-red-plus-avahi/Dockerfile b/hub.docker.com/bland328/node-red-plus-avahi/Dockerfile
--- a/hub.docker.com/bland328/node-red-plus-avahi/Dockerfile
+++ b/hub.docker.com/bland328/node-red-plus-avahi/Dockerfile
@@ -1,80 +1,86 @@
-# bland328/node-red-plus-homekit Dockerfile
+# bland328/node-red-plus-avahi Dockerfile
 #
 # Node-RED Dockerfile with integrated Avahi to support node-red-contrib-homekit-bridged
 #
-# Intended for unRAID, but may serve others well
+# Build for use with Unraid, but know of no specific provisions that would preclude other uses
+#
 # Based heavily upon https://github.com/mschm/node-red-contrib-homekit/issues/8#issuecomment-362029068
 #
 # Build reminders to myself, as I don't deal with this very often:
 #   1) AUTOBUILD IS ON AT https://cloud.docker.com/swarm/bland328/repository/docker/bland328/node-red-plus-homekit/general
 #      SO ANY PUSHED CHANGE HERE RESULTS IN A BUILD BASED ON THE LATEST OFFICIAL NODE-RED DOCKER CONTAINER.
 #   2) I also have REPOSITORY LINKS turned on at Docker Hub, so any change to the Base Image (in this case, the
-#      official Node-RED Docker Container) also results in an auto-build.
+#      official Node-RED Docker Container) would also theoretically result in an auto-build; it is currently unclear
+#      whether this nifty Docker Hub feature is broken.
 #
 # The resulting build is at https://store.docker.com/community/images/bland328/node-red-plus-homekit
 
-# Overview:
-# Based on the offical Node-RED docker
-# add gosu (per https://github.com/tianon/gosu/blob/master/INSTALL.md)
-# add avahi-daemon
-# configure avahi-daemon execution
-# DISABLED, AS THIS NEEDS TO BE INSTALLED BY THE USER: add node-red-contrib-homekit-bridged
-# add entrypoint.sh
+# TODO:
+#   Consider replacing gosu with su-exec per https://github.com/tianon/gosu/blob/master/INSTALL.md: "Note: when using Alpine, it's probably also worth checking out su-exec (apk add --no-cache su-exec) instead, which since version 0.2 is fully gosu-compatible in a fraction of the file size."
 
-# Declare a Docker image on which to build
-FROM nodered/node-red-docker
+# Overview:
+#   Based on offical Node-RED docker
+#     + Add gosu (per https://github.com/tianon/gosu/blob/master/INSTALL.md)
+#     + Add avahi-daemon
+#     + Configure avahi-daemon execution
+#     + Add entrypoint.sh
+
+# Declare a Docker image on which to build (2020-01-07: Moved to newer official Node-RED base image)
+FROM nodered/node-red:latest
 
 # Become root
 USER root
 
-# Download and install gosu
+# Download and install gosu (per https://github.com/tianon/gosu/blob/master/INSTALL.md)
 ENV GOSU_VERSION 1.11
-RUN set -ex; \
-    \
-    fetchDeps=' \
-        ca-certificates \
-        wget \
-    '; \
-    apt-get update; \
-    apt-get install -y --no-install-recommends $fetchDeps; \
-    rm -rf /var/lib/apt/lists/*; \
-    \
-    dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
-    wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
-    wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
-    \
-    # verify the signature
-    export GNUPGHOME="$(mktemp -d)"; \
-    key="B42F6819007F00F88E364FD4036A9C25BF357DD4"; \
-    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" || \
-    gpg --keyserver pgp.mit.edu --recv-keys "$key" || \
-    gpg --keyserver keyserver.pgp.com --recv-keys "$key"; \
-    gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
-    rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc; \
-    \
-    chmod +x /usr/local/bin/gosu; \
-    # verify the binary works
-    gosu nobody true; \
-    \
-    apt-get purge -y --auto-remove $fetchDeps
-
+RUN set -eux; \
+	\
+	apk add --no-cache --virtual .gosu-deps \
+		ca-certificates \
+		dpkg \
+		gnupg \
+	; \
+	\
+	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+	\
+    # Verify signature
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+	command -v gpgconf && gpgconf --kill all || :; \
+	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+	\
+    # Clean up fetch dependencies
+	apk del --no-network .gosu-deps; \
+	\
+	chmod +x /usr/local/bin/gosu; \
+    # Verify binary works
+	gosu --version; \
+	gosu nobody true
+    
 # Set gosu ownership and permissions
 RUN chown root:node-red /usr/local/bin/gosu && chmod +s /usr/local/bin/gosu
 
-# Get avahi-daemon et al
-RUN apt-get update -y && apt-get install -y apt-utils build-essential python make g++ avahi-daemon avahi-discover libnss-mdns libavahi-compat-libdnssd-dev
+# Install OpenRC init system, avahi-daemon and more
+RUN apk add --no-cache \
+	openrc \
+	dbus \
+	make \
+	g++ \
+	avahi \
+	avahi-dev \
+	; \
+	rm -rf /var/cache/apk/*
 
 # Configure avahi-daemon
-RUN sed -i "s/#enable-dbus=yes/enable-dbus=yes/g" /etc/avahi/avahi-daemon.conf
-RUN mkdir -p /var/run/dbus && mkdir -p /var/run/avahi-daemon
-RUN chown messagebus:messagebus /var/run/dbus && chown avahi:avahi /var/run/avahi-daemon && dbus-uuidgen --ensure
+RUN sed -i "s/#enable-dbus=yes/enable-dbus=yes/g" /etc/avahi/avahi-daemon.conf && \
+	mkdir -p /var/run/dbus && mkdir -p /var/run/avahi-daemon && \
+	chown messagebus:messagebus /var/run/dbus && chown avahi:avahi /var/run/avahi-daemon && dbus-uuidgen --ensure
 
 # Become user node-red
 USER node-red
-
-# Install node-red-contrib-homekit-bridged
-# CURRENTLY DISABLED, AS THIS NEEDS TO BE INSTALLED BY THE USER, AFTER THE PERSISTANT /data DIR EXISTS
-# RUN cd /data && npm install node-red-contrib-homekit-bridged
 
 # Incorporate entrypoint.sh file, set its permissions, and declare it the entrypoint for the container
 COPY entrypoint.sh /usr/src/node-red
diff --git a/hub.docker.com/broadiq/mongodb/Dockerfile b/hub.docker.com/broadiq/mongodb/Dockerfile
--- a/hub.docker.com/broadiq/mongodb/Dockerfile
+++ b/hub.docker.com/broadiq/mongodb/Dockerfile
@@ -1,22 +1,56 @@
-FROM mongo:3.6
+FROM base/archlinux:latest
 
-MAINTAINER <John S. Lutz> jlutz@broadiq.com
+# Build arguments.
+ARG VCS_REF
+ARG BUILD_DATE
+ARG BRINKOS_VERSION="2018.07.15"
 
-ENV AUTH yes
+# Labels / Metadata.
+LABEL maintainer="James Brink, brink.james@gmail.com" \
+    decription="brinkOS" \
+    version="${BRINKOS_VERSION}" \
+    org.label-schema.name="brinkos" \
+    org.label-schema.build-date=$BUILD_DATE \
+    org.label-schema.vcs-ref=$VCS_REF \
+    org.label-schema.vcs-url="https://github.com/jamesbrink/brinkos" \
+    org.label-schema.schema-version="1.0.0-rc1"
 
-ENV MONGODB_ADMIN_USER root 
-# ENV MONGODB_ADMIN_PASS password
+# Create user for builds.
+RUN set -xe; \
+    useradd --no-create-home --shell=/bin/false build; \
+    usermod -L build; \
+    echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers; \
+    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers;
 
-# ENV MONGODB_APPLICATION_DATABASE your_db
-# ENV MONGODB_APPLICATION_USER user
-# ENV MONGODB_APPLICATION_PASS password
+# Install all needed deps
+RUN set -xe; \
+    pacman -Syyu --noconfirm; \
+    pacman -S base base-devel cmake automake autoconf wget vim archiso openssh git nginx --noconfirm;
 
-EXPOSE 27017 27017
+# Improve build time by caching packages from image.
+COPY ./pacman.conf /etc/pacman.conf
+COPY ./packages.txt /packages.txt
+COPY ./pacstrap.sh /bin/pacstrap
+RUN pacman --noconfirm -Syyw $(</packages.txt)
 
-ADD run-config.sh /run-config.sh
-ADD set-password.sh /set-password.sh
+# If building on a debian host, dev/shm points to /run/shm
+# and will fail without this directory.
+RUN mkdir -p /build/archiso/work/x86_64/airootfs/run/shm; \
+    mkdir -p /build/archiso/work/x86_64/airootfs/var/run/shm; \
+    mkdir -p /run/shm; \
+    mkdir -p /var/run/shm;
 
-RUN chmod +x /run-config.sh
-RUN chmod +x /set-password.sh
+# Copy in our entrypoint and archlive and set ownership.
+COPY ./archlive /build/archlive
+COPY ./docker-entrypoint.sh /build/docker-entrypoint.sh
 
-CMD ["/run-config.sh"]
+# Setup Environment variables.
+ENV GTK_THEME="brinkOS-Dark" \
+    SHELL_THEME="brinkOS-Dark" \
+    ICON_THEME="brinkOS" \
+    WALLPAPER="file:///usr/share/backgrounds/gnome/mountain-top.jpg" \
+    PACKAGE_PROXY="" \
+    NETINSTALL="true"
+
+# Set our entrypoint which kicks off our build.
+ENTRYPOINT [ "/build/docker-entrypoint.sh" ]
diff --git a/hub.docker.com/cbeier/debian-drupal-php-node/Dockerfile b/hub.docker.com/cbeier/debian-drupal-php-node/Dockerfile
--- a/hub.docker.com/cbeier/debian-drupal-php-node/Dockerfile
+++ b/hub.docker.com/cbeier/debian-drupal-php-node/Dockerfile
@@ -1,11 +1,33 @@
-FROM cbeier/drupal-php:latest
+FROM postgres:10.7
 
-RUN curl -sL https://deb.nodesource.com/setup_7.x | bash - && \
-    apt-get update && \
-    apt-get install -y \
-        nano \
-        curl \
-        php5-curl \
-        nodejs && \
-    npm install gulp -g && \
-    rm -rf /var/lib/apt/lists/*
+MAINTAINER cavamagie
+
+ENV POSTGIS_MAJOR 2.4
+ENV POSTGRES_USER postgres
+ENV POSTGRES_PASS postgres
+ENV BACKUP_DIR '/var/lib/postgresql/backup-db'
+ENV DBHOST localhost
+ENV PGPASSWORD **None**
+ENV DBNAMES 'all'
+ENV SCHEDULE '@daily'
+COPY files/autopgsqlbackup.sh ./
+RUN chmod -R 777 autopgsqlbackup.sh
+RUN apt-get update \
+      && apt-get install -y -f \
+      postgresql-10-postgis-$POSTGIS_MAJOR \
+     # postgresql-10-postgis-$POSTGIS_MAJOR-scripts \
+      && rm -rf /var/lib/apt/lists/*
+
+# cleanup
+RUN apt-get -qy autoremove
+
+
+RUN mkdir -p /docker-entrypoint-initdb.d
+
+
+
+
+VOLUME /backups
+
+HEALTHCHECK --interval=5m --timeout=5s \
+  CMD pg_isready || exit 1
diff --git a/hub.docker.com/cinemast/hello-docker-multiarch/Dockerfile b/hub.docker.com/cinemast/hello-docker-multiarch/Dockerfile
--- a/hub.docker.com/cinemast/hello-docker-multiarch/Dockerfile
+++ b/hub.docker.com/cinemast/hello-docker-multiarch/Dockerfile
@@ -1,12 +1,160 @@
-FROM alpine:latest AS builder
-RUN /bin/mkdir /build
-WORKDIR /build
-COPY Makefile main.cpp httplib.h /build/
-RUN apk add --no-cache g++ libc-dev make
-RUN make hello-world
+FROM ubuntu:16.04
 
-ARG target_arch
-FROM alpine:latest
-RUN apk add --no-cache libstdc++
-COPY --from=builder /build/hello-world /usr/bin/hello-world
-CMD ["/usr/bin/hello-world"]
+## Avoid warnings by switching to noninteractive
+ENV DEBIAN_FRONTEND=noninteractive
+
+# Docker Compose version
+ARG COMPOSE_VERSION=1.24.0
+ARG KOMPOSE_VERSION=1.19.0
+ARG HELMFILE_VERSION=0.87.1
+ARG NODEJS_VERSION=13
+
+## This Dockerfile adds a non-root 'vscode' user with sudo access. However, for Linux,
+## this user's GID/UID must match your local user UID/GID to avoid permission issues
+## with bind mounts. Update USER_UID / USER_GID if yours is not 1000. See
+## https://aka.ms/vscode-remote/containers/non-root-user for details.
+ARG USERNAME=vscode
+ARG USER_UID=1000
+ARG USER_GID=$USER_UID
+
+## apt-get and system utilities
+RUN apt-get update \
+    && apt-get install -yq --no-install-recommends apt-utils dialog 2>&1 \
+        apt-transport-https \
+        debconf-utils \
+        ca-certificates \
+        build-essential \
+        lsb-release \
+        software-properties-common \
+        iproute2 \ 
+        procps \
+        dirmngr \
+        iputils-ping \
+        net-tools \
+        telnet \
+        dnsutils \
+        nano \
+        wget \
+        curl \
+        p7zip-full p7zip-rar \
+        git \
+        jq \
+        mc \
+        # https://linuxize.com/post/how-to-use-linux-screen/
+        screen \
+    && rm -rf /var/lib/apt/lists/*
+
+## PlantUML https://github.com/microsoft/vscode-dev-containers/blob/master/containers/plantuml/.devcontainer/Dockerfile
+RUN apt-get update \
+    && apt-get install -yq --no-install-recommends graphviz default-jre \
+    && mkdir -p /opt/plantuml \
+    && (cd /opt/plantuml; curl -JLO http://sourceforge.net/projects/plantuml/files/plantuml.jar/download) \
+    && echo '#!/bin/sh \njava -jar /opt/plantuml/plantuml.jar "$@" \n' > /usr/local/bin/plantuml \
+    && chmod a+x /usr/local/bin/plantuml \
+    && rm -rf /var/lib/apt/lists/*
+
+## Docker https://github.com/microsoft/vscode-dev-containers/blob/master/containers/kubernetes-helm/.devcontainer/Dockerfile
+RUN apt-get update \
+    && apt-get install -yq --no-install-recommends apt-transport-https ca-certificates curl gnupg-agent software-properties-common lsb-release \
+    && curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
+    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" \
+    && apt-get update \
+    && apt-get install -y docker-ce-cli \
+    && curl -sSL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
+    && chmod +x /usr/local/bin/docker-compose \
+    && rm -rf /var/lib/apt/lists/*
+
+## Powershell https://github.com/microsoft/vscode-dev-containers/blob/master/containers/powershell/.devcontainer/Dockerfile
+## DotNet Core https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dotnetcore-latest/.devcontainer/Dockerfile
+RUN wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb \
+    && dpkg -i packages-microsoft-prod.deb \
+    && apt-get update && apt-get install -yq --no-install-recommends \
+        powershell \
+        dotnet-sdk-3.0 \
+        # dotnet-runtime-3.0 \
+        # aspnetcore-runtime-3.0 \
+    && rm -rf /var/lib/apt/lists/*
+
+## Azure-CLI https://github.com/microsoft/vscode-dev-containers/blob/master/containers/azure-cli/.devcontainer/Dockerfile
+RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/azure-cli.list \
+    && curl -sL https://packages.microsoft.com/keys/microsoft.asc | apt-key add - 2>/dev/null \
+    && apt-get update && apt-get install -yq --no-install-recommends \
+        azure-cli \
+    && rm -rf /var/lib/apt/lists/*
+
+## Google Cloud, Kubectl
+RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
+    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - \
+    && apt-get update && apt-get install -yq --no-install-recommends \
+        google-cloud-sdk \
+        kubectl \
+    && rm -rf /var/lib/apt/lists/*
+
+## Kompose
+RUN curl -L https://github.com/kubernetes/kompose/releases/download/v${KOMPOSE_VERSION}/kompose-linux-amd64 -o kompose \
+    && chmod +x kompose \
+    && mv ./kompose /usr/local/bin/kompose
+
+## Helm, HelmFile https://github.com/microsoft/vscode-dev-containers/blob/master/containers/kubernetes-helm/.devcontainer/Dockerfile
+RUN apt-get update && apt-get install -yq --no-install-recommends sudo \
+    && curl -L https://git.io/get_helm.sh | bash \
+    && helm init --client-only \
+    && mkdir -p ~/.helm/plugins \
+    && helm plugin install https://github.com/databus23/helm-diff \
+    && helm plugin install https://github.com/futuresimple/helm-secrets \
+    && helm plugin install https://github.com/hypnoglow/helm-s3.git \
+    && helm plugin install https://github.com/aslafy-z/helm-git.git \
+    && helm plugin install https://github.com/rimusz/helm-tiller \
+    && curl -L https://github.com/roboll/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_linux_amd64 -o /usr/local/bin/helmfile \
+    && chmod +x /usr/local/bin/helmfile
+
+## NodeJs w/ NPM https://github.com/microsoft/vscode-dev-containers/blob/master/containers/typescript-node-lts/.devcontainer/Dockerfile
+RUN curl -sL https://deb.nodesource.com/setup_${NODEJS_VERSION}.x | bash - \
+    && apt-get update && apt-get install -yq --no-install-recommends \
+        nodejs \
+    && rm -rf /var/lib/apt/lists/*
+
+## TypeScript, tsLint, Angular, CloudCmd, Gritty
+RUN npm config set user 0 \
+    && npm install --production -g \
+        tslint typescript \
+        @angular/cli \
+        cloudcmd \
+        gritty
+
+## Virtual Screen https://linuxize.com/post/how-to-use-linux-screen/
+RUN apt-get update && apt-get install -yq --no-install-recommends \
+        screen \
+    && rm -rf /var/lib/apt/lists/*
+
+## Oh My Zsh
+RUN apt-get update && apt-get install -yq --no-install-recommends \
+        fonts-powerline \
+        zsh \
+    && apt-get update \
+    && sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" \
+    && sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="robbyrussell"/g' ~/.zshrc \
+    && sed -i 's/plugins=(git)/plugins=(git copydir docker docker-compose helm kubectl minikube node npm ubuntu)/g' ~/.zshrc \
+    && rm -rf /var/lib/apt/lists/*
+
+## Create a non-root user to use if preferred - see https://aka.ms/vscode-remote/containers/non-root-user.
+RUN groupadd --gid $USER_GID $USERNAME \
+    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
+    # [Optional] Add sudo support for the non-root user
+    && apt-get install -yq --no-install-recommends sudo \
+    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
+    && chmod 0440 /etc/sudoers.d/$USERNAME
+
+## Clean up
+RUN apt-get update \
+    && apt-get autoremove -yq \
+    && apt-get clean -yq \
+    && rm -rf /var/lib/apt/lists/*
+
+## Switch back to dialog for any ad-hoc use of apt-get
+ENV DEBIAN_FRONTEND=
+
+## 
+EXPOSE 8000
+
+# ENTRYPOINT ["tail", "-f", "/dev/null"]
diff --git a/hub.docker.com/felixbuenemann/node-nginx-base-docker/Dockerfile b/hub.docker.com/felixbuenemann/node-nginx-base-docker/Dockerfile
--- a/hub.docker.com/felixbuenemann/node-nginx-base-docker/Dockerfile
+++ b/hub.docker.com/felixbuenemann/node-nginx-base-docker/Dockerfile
@@ -1,109 +1,107 @@
-FROM alpine:3.8
-MAINTAINER Felix Buenemann <buenemann@louis.info>
+FROM ubuntu:16.04
 
-ENV NGINX_VERSION 1.16.0
-ENV NGINX_GPG_KEY B0F4253373F8F6F510D42178520A9993A1C052F8
-ENV CLOUDFLARE_ZLIB_REF af9ef2e94cb9ffebc8dc6cc6d856e494880d869b
-ENV ACCEPT_LANGUAGE_MODULE_REF 2f69842f83dac77f7d98b41a2b31b13b87aeaba7
-ENV BROTLI_MODULE_REF 8104036af9cff4b1d34f22d00ba857e2a93a243c
-ENV BROTLI_LIBRARY_REF d6d98957ca8ccb1ef45922e978bb10efca0ea541
+MAINTAINER Feivur
 
-ADD stack-fix.c /tmp/
+ENV ANDROID_HOME /opt/android-sdk
+#ENV ANDROID_NDK  /opt/android-ndk
+#ENV ANDROID_NDK_HOME /opt/android-ndk
 
-RUN set -x \
-  && addgroup -g 1000 node \
-  && adduser -u 1000 -G node -s /bin/sh -D node \
-  && addgroup -S nginx \
-  && adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
-  && apk update && apk upgrade \
-  && apk add bash openssl pcre ca-certificates libintl geoip nodejs npm yarn \
-  && apk add --virtual .build-deps build-base linux-headers gettext gnupg geoip-dev openssl-dev pcre-dev \
-  && gcc  -shared -fPIC /tmp/stack-fix.c -o /usr/local/lib/stack-fix.so \
-  && strip /usr/local/lib/stack-fix.so \
-  && rm /tmp/stack-fix.c \
-  && mkdir -p /tmp/src \
-  # get nginx_accept_language_module:
-  && cd /tmp/src \
-  && wget -O nginx_accept_language_module.tgz https://github.com/giom/nginx_accept_language_module/archive/${ACCEPT_LANGUAGE_MODULE_REF}.tar.gz \
-  && tar xzf nginx_accept_language_module.tgz \
-  # get ngx_brotli:
-  && cd /tmp/src \
-  && wget -O ngx_brotli.tgz https://github.com/eustas/ngx_brotli/archive/${BROTLI_MODULE_REF}.tar.gz \
-  && tar xzf ngx_brotli.tgz \
-  # get brotli lib for ngx_brotli:
-  && cd /tmp/src \
-  && wget -O brotli.tgz https://github.com/google/brotli/archive/${BROTLI_LIBRARY_REF}.tar.gz \
-  && tar xzf brotli.tgz \
-  && rmdir ngx_brotli-${BROTLI_MODULE_REF}/deps/brotli \
-  && mv brotli-${BROTLI_LIBRARY_REF} ngx_brotli-${BROTLI_MODULE_REF}/deps/brotli \
-  # get cloudflare zlib fork:
-  && cd /tmp/src \
-  && wget -O zlib.tgz https://github.com/cloudflare/zlib/archive/${CLOUDFLARE_ZLIB_REF}.tar.gz \
-  && tar xzf zlib.tgz \
-  && cd /tmp/src/zlib-${CLOUDFLARE_ZLIB_REF} \
-  && make -f Makefile.in distclean \
-  # install nginx:
-  && cd /tmp/src \
-  && wget -O nginx.tgz https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
-  && wget -O nginx.tgz.asc https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz.asc \
-  && export GNUPGHOME=$PWD \
-  && gpg --keyserver hkp://keyserver.ubuntu.com:80 --keyserver-options timeout=10 --recv-keys $NGINX_GPG_KEY \
-  && gpg --batch --verify nginx.tgz.asc nginx.tgz \
-  && tar xzf nginx.tgz \
-  && cd /tmp/src/nginx-${NGINX_VERSION} \
-  && ./configure \
-    --prefix=/etc/nginx \
-    --sbin-path=/usr/sbin/nginx \
-    --conf-path=/etc/nginx/nginx.conf \
-    --pid-path=/run/nginx.pid \
-    --lock-path=/run/nginx.lock \
-    --http-log-path=/var/log/nginx/access.log \
-    --error-log-path=/var/log/nginx/error.log \
-    --http-client-body-temp-path=/var/cache/nginx/client_temp \
-    --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
-    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
-    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
-    --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
-    --user=nginx \
-    --group=nginx \
-    --with-zlib=/tmp/src/zlib-${CLOUDFLARE_ZLIB_REF} \
-    --with-pcre-jit \
-    --with-http_ssl_module \
-    --with-stream_ssl_module \
-    --with-http_stub_status_module \
-    --with-http_gzip_static_module \
-    --with-http_gunzip_module \
-    --with-http_v2_module \
-    --with-http_auth_request_module \
-    --with-http_realip_module \
-    --with-http_geoip_module \
-    --add-module=/tmp/src/nginx_accept_language_module-${ACCEPT_LANGUAGE_MODULE_REF} \
-    --add-module=/tmp/src/ngx_brotli-${BROTLI_MODULE_REF} \
-  && make -s V=0 install \
-  # forward request and error logs to docker log collector
-  && ln -sf /dev/stdout /var/log/nginx/access.log \
-  && ln -sf /dev/stderr /var/log/nginx/error.log \
-  # move envsubst to /usr/local so it's not deleted
-  && cp /usr/bin/envsubst /usr/local/bin/ \
-  # remove build files and dependencies
-  && rm -rf /tmp/src \
-  && apk del --purge .build-deps \
-  && rm -rf /var/cache/apk/*
+# Get the latest version from https://developer.android.com/studio/index.html
+# ENV ANDROID_SDK_VERSION="28"
+# Get the latest version from https://developer.android.com/ndk/downloads/index.html
+#ENV ANDROID_NDK_VERSION="15"
 
-ENV LD_PRELOAD=/usr/local/lib/stack-fix.so
+# Set locale
+ENV LANG en_US.UTF-8
+RUN apt-get clean && apt-get update && apt-get install -y locales
+RUN locale-gen $LANG
 
-ARG FOREGO_URL=https://bin.equinox.io/a/c6JW1BqJwSa/forego-20170327195458-linux-amd64.tar.gz
-ARG FOREGO_SHA256=ebea36e8326cdbc9cca15f946c13eb7b91c73bce61bcc2fd6ae7984e825b81d0
-RUN set -x \
-  && cd /tmp \
-  && wget -O forego.tgz $FOREGO_URL \
-  && echo "$FOREGO_SHA256 *forego.tgz" | sha256sum -cs \
-  && tar xzf forego.tgz \
-  && chmod +x forego \
-  && mv forego /usr/local/bin/ \
-  && rm forego.tgz
+COPY README.md /README.md
 
-# alpine's nodejs is compiled with small-icu, download full-icu
-ENV FULL_ICU_VERSION=1.2.1
-RUN su node -c "cd && npm install --silent --no-package-lock --prod full-icu@${FULL_ICU_VERSION}" >/dev/null
-ENV NODE_ICU_DATA /home/node/node_modules/full-icu
+WORKDIR /tmp
+
+# Installing packages
+RUN apt-get update && \
+	apt-get install -y --no-install-recommends \
+		build-essential \
+		autoconf \
+		git \
+		curl \
+		wget \
+		lib32stdc++6 \
+		lib32z1 \
+		lib32z1-dev \
+		lib32ncurses5 \
+		libc6-dev \
+		libgmp-dev \
+		libmpc-dev \
+		libmpfr-dev \
+		libxslt-dev \
+		libxml2-dev \
+		m4 \
+		ncurses-dev \
+		ocaml \
+		openssh-client \
+		pkg-config \
+		python-software-properties \
+		software-properties-common \
+		unzip \
+		zip \
+		mercurial \
+		mc \
+		zlib1g-dev && \
+	apt-add-repository -y ppa:openjdk-r/ppa && \
+	apt-get install -y openjdk-8-jdk && \
+	rm -rf /var/lib/apt/lists/ && \
+	apt-get clean
+
+ENV HGAPP /usr/bin/hg
+
+# Install Android SDK
+# new 28: https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
+# old https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
+RUN wget -q -O tools.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip && \
+	unzip -q tools.zip && \
+	rm -fr $ANDROID_HOME tools.zip && \
+	mkdir -p $ANDROID_HOME && \
+	mv tools $ANDROID_HOME/tools
+
+	# Install Android components
+RUN yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
+RUN	cd $ANDROID_HOME && \
+	echo y | tools/bin/sdkmanager "build-tools;27.0.2"  && \
+	echo y | tools/bin/sdkmanager "build-tools;28.0.3"  && \
+	echo y | tools/bin/sdkmanager "build-tools;29.0.2"  && \
+	echo y | tools/bin/sdkmanager "platforms;android-27"  && \
+	echo y | tools/bin/sdkmanager "platforms;android-28"  && \
+	echo y | tools/bin/sdkmanager "platforms;android-29"  && \
+	echo y | tools/bin/sdkmanager "extras;android;m2repository"  && \
+	echo y | tools/bin/sdkmanager "extras;google;google_play_services"  && \
+	echo y | tools/bin/sdkmanager "extras;google;m2repository"  && \
+	echo y | tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"  && \
+	echo y | tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"  && \
+	echo y | tools/bin/sdkmanager "platform-tools"
+
+
+# Install Android NDK, put it in a separate RUN to avoid travis-ci timeout in 10 minutes.
+#RUN wget -q -O android-ndk.zip http://dl.google.com/android/repository/android-ndk-r${ANDROID_NDK_VERSION}-linux-x86_64.zip && \
+#	unzip -q android-ndk.zip && \
+#	rm -fr $ANDROID_NDK android-ndk.zip && \
+#	mv android-ndk-r${ANDROID_NDK_VERSION} $ANDROID_NDK
+
+# Add android commands to PATH
+ENV ANDROID_SDK_HOME $ANDROID_HOME
+ENV PATH $PATH:$ANDROID_SDK_HOME/tools:$ANDROID_SDK_HOME/platform-tools:$ANDROID_NDK
+
+# Export JAVA_HOME variable
+ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
+
+# Support Gradle
+ENV TERM dumb
+ENV JAVA_OPTS "-Xms4096m -Xmx4096m"
+ENV GRADLE_OPTS "-XX:+UseG1GC -XX:MaxGCPauseMillis=1000"
+
+# Confirms that we agreed on the Terms and Conditions of the SDK itself
+# (if we didn’t the build would fail, asking us to agree on those terms).
+RUN mkdir "${ANDROID_HOME}/licenses" || true
+RUN echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
